const VIDEO_OFFSET_RATIO = 0.2
const REVEAL_SIZE = 200
const SOUND_URL = '/sounds/static-noise.mp3'
const SOUND_VOLUME = 0.0075
const FADE_DURATION = 300
const FADE_STEP_INTERVAL = 16

export {
    VIDEO_OFFSET_RATIO,
    REVEAL_SIZE,
    SOUND_URL,
    SOUND_VOLUME,
    FADE_DURATION,
    FADE_STEP_INTERVAL
}