const TRUNCATE_LENGTHS = {
    PANEL_NAME: 26,
    PANEL_AGENT_SUBTITLE: 18,
    NODE_AGENT_NAME: 21,
    NODE_AGENT_NAME_SHORT: 7,
    SIDEBAR_AGENT_NAME: 13,
    SIDEBAR_AGENT_NAME_FULL: 11
}

export default TRUNCATE_LENGTHS