import type {
    GitHubFileEntry,
    GitHubPullRequestResponse,
    GitHubRefResponse
} from '@/ts/Interfaces'

import { externalUrls, httpMethod } from '@openclaw/shared'

const GITHUB_OWNER = 'bfzli'
const GITHUB_REPO_NAME = 'clawhost'
const BLOG_PATH = 'apps/web/content/posts'
const BASE_BRANCH = 'Production'

const github = externalUrls.GITHUB.repo(GITHUB_OWNER, GITHUB_REPO_NAME)

const GITHUB_HEADERS = (token: string) => ({
    Authorization: `Bearer ${token}`,
    Accept: 'application/vnd.github.v3+json',
    'Content-Type': 'application/json'
})

const githubApi = {
    async fetchExistingSlugs(token: string): Promise<string[]> {
        const res = await fetch(github.CONTENTS(BLOG_PATH, BASE_BRANCH), {
            headers: GITHUB_HEADERS(token)
        })

        if (!res.ok) return []

        const files = (await res.json()) as GitHubFileEntry[]
        return files
            .filter((f) => f.name.endsWith('.mdx'))
            .map((f) => f.name.replace('.mdx', ''))
    },

    async getProductionSha(token: string): Promise<string | null> {
        const res = await fetch(github.REF(BASE_BRANCH), {
            headers: GITHUB_HEADERS(token)
        })

        if (!res.ok) return null

        const data = (await res.json()) as GitHubRefResponse
        return data.object.sha
    },

    async createBranch(
        token: string,
        branchName: string,
        baseSha: string
    ): Promise<boolean> {
        const res = await fetch(github.REFS, {
            method: httpMethod.POST,
            headers: GITHUB_HEADERS(token),
            body: JSON.stringify({
                ref: `refs/heads/${branchName}`,
                sha: baseSha
            })
        })

        return res.ok
    },

    async pushFile(
        token: string,
        slug: string,
        content: string,
        branch: string
    ): Promise<boolean> {
        const filePath = `${BLOG_PATH}/${slug}.mdx`
        const encoded = Buffer.from(content).toString('base64')

        const res = await fetch(github.CONTENTS(filePath), {
            method: httpMethod.PUT,
            headers: GITHUB_HEADERS(token),
            body: JSON.stringify({
                message: `blog: add "${slug}"`,
                content: encoded,
                branch
            })
        })

        return res.ok
    },

    async createPullRequest(
        token: string,
        branchName: string,
        title: string,
        slug: string
    ): Promise<string | null> {
        const res = await fetch(github.PULLS, {
            method: httpMethod.POST,
            headers: GITHUB_HEADERS(token),
            body: JSON.stringify({
                title: `blog: ${title}`,
                head: branchName,
                base: BASE_BRANCH,
                body: `## Auto-generated blog post\n\n**Slug:** \`${slug}\`\n**Title:** ${title}\n\nGenerated by the ClawHost blog pipeline using OpenAI web search for trending topics.`
            })
        })

        if (!res.ok) return null

        const data = (await res.json()) as GitHubPullRequestResponse
        return data.html_url
    },

    async mergePullRequest(token: string, prUrl: string): Promise<boolean> {
        const prNumber = prUrl.split('/').pop()!
        const res = await fetch(github.PULL_MERGE(prNumber), {
            method: httpMethod.PUT,
            headers: GITHUB_HEADERS(token),
            body: JSON.stringify({
                merge_method: 'squash'
            })
        })

        return res.ok
    },

    async deleteBranch(token: string, branchName: string): Promise<void> {
        await fetch(github.DELETE_REF(branchName), {
            method: httpMethod.DELETE,
            headers: GITHUB_HEADERS(token)
        })
    }
}

export default githubApi