name: Deploy API

on:
    push:
        branches: [Production]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - run: |
                  curl -X GET "https://console.bfzli.com/api/v1/deploy?uuid=blqsgtd33wew5zhvkdo7057v&force=false" \
                    -H "Authorization: Bearer ${{ secrets.COOLIFY_API_TOKEN }}"
